### PR TITLE
Require unittest2 only if we use Python < 2.7

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by gforcada** [comment]
Using python < 2.7 means maximum 2.6, which is only supported by Plone 4.3, should we rather cleanup unittest2 references and make a major release so that 4.3 can point to the previous release and free master from python < 2.7 ?

**Comment by ale-rt** [comment]
Waiting for this one to be merged: https://github.com/plone/plone.app.contentlisting/pull/25

**Comment by ale-rt** [comment]
Please merge after plone/plone.app.contentlisting#25

**Comment by jensens** [comment]
merged plone/plone.app.contentlisting#25

**Comment by ale-rt** [comment]
This is also ready to merge, @jensens

**Comment by jensens** [comment]
should we first branch away for 4.3?

**Comment by ale-rt** [comment]
I do not know how to handle this properly.
I already updated the setup.py, see:
- https://github.com/plone/plone.resource/pull/19/files#diff-2eeaed663bd0d25b7e608891384b7298L18

Maybe I should push a branch from the current master called 1.2.x and modify the mr.developer sources in the 4.3 branch of buildout.coredev to checkout that branch.
Is this correct?
Should I do something else?

**Comment by jensens** [comment]
I created a 1.x branch and set coredev 4.3 to use it

**Pull request merged**
